baseurl = "https://akhil.codes"
title = "Akhil Tulluri"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Akhil Tulluri"
  info = "Student Developer"
  description = "Akhil's personal portfolio/blog"
  keywords = "blog,developer,personal,portfolio"
  avatarurl = "images/akhil.gif"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/officialakhil/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/AkhilCodes/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/akhilcodes/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
# [[menu.main]]
  # name = "Blog"
  # weight = 2
  # url  = "posts/"
# [[menu.main]]
  # name = "Projects"
  # weight = 3
  # url  = "projects/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"